import { type RouteConfig, index, layout, prefix, route } from '@react-router/dev/routes';

// Routes — RR v7 framework mode.
// Surface map: (public), (auth), dashboard, broker, admin, agent + /b/:slug.

export default [
  layout('(public)/_layout.tsx', [
    index('(public)/page.tsx'),
    route('search', '(public)/search/page.tsx'),
    route('listing/:id', '(public)/listing.$id/page.tsx'),
    route('map', '(public)/map/page.tsx'),
    route('compare', '(public)/compare/page.tsx'),
    route('post-listing', '(public)/post-listing/page.tsx'),
    route('tools/valuation', '(public)/tools.valuation/page.tsx'),
    route('tools/investment-sim', '(public)/tools.investment-sim/page.tsx'),
    route('regions', '(public)/regions/page.tsx'),
    route('about', '(public)/about/page.tsx'),
    route('pricing', '(public)/pricing/page.tsx'),
    route('legal/:doc', '(public)/legal.$doc/page.tsx'),
    route('contact', '(public)/contact/page.tsx'),
    route('help', '(public)/help/page.tsx'),
    route('notifications', '(public)/notifications/page.tsx'),
    route('blog', '(public)/blog/page.tsx'),
    route('blog/:slug', '(public)/blog.$slug/page.tsx'),
    route('design', '(public)/design/page.tsx'),
    route('b/:slug', 'b.$slug/page.tsx'),
  ]),

  layout('(auth)/_layout.tsx', [
    route('login', '(auth)/login/page.tsx'),
    route('register', '(auth)/register/page.tsx'),
    route('forgot', '(auth)/forgot/page.tsx'),
    route('reset', '(auth)/reset/page.tsx'),
    route('verify', '(auth)/verify/page.tsx'),
    route('passkey-setup', '(auth)/passkey-setup/page.tsx'),
  ]),

  ...prefix('dashboard', [
    layout('dashboard/_layout.tsx', [
      index('dashboard/page.tsx'),
      route('listings', 'dashboard/listings/page.tsx'),
      route('favorites', 'dashboard/favorites/page.tsx'),
      route('favorites/trends', 'dashboard/favorites.trends/page.tsx'),
      route('ai-history', 'dashboard/ai-history/page.tsx'),
      route('viewings', 'dashboard/viewings/page.tsx'),
      route('alerts', 'dashboard/alerts/page.tsx'),
      route('messages', 'dashboard/messages/page.tsx'),
      route('ai', 'dashboard/ai/page.tsx'),
      route('security', 'dashboard/security/page.tsx'),
      route('profile', 'dashboard/profile/page.tsx'),
      route('billing', 'dashboard/billing/page.tsx'),
      route('kyc', 'dashboard/kyc/page.tsx'),
    ]),
  ]),

  ...prefix('broker', [
    layout('broker/_layout.tsx', [
      index('broker/page.tsx'),
      route('portfolio', 'broker/portfolio/page.tsx'),
      route('leads', 'broker/leads/page.tsx'),
      route('clients', 'broker/clients/page.tsx'),
      route('commissions', 'broker/commissions/page.tsx'),
      route('showcase', 'broker/showcase/page.tsx'),
      route('team', 'broker/team/page.tsx'),
      route('analytics', 'broker/analytics/page.tsx'),
      route('performance', 'broker/performance/page.tsx'),
      route('ai-tools', 'broker/ai-tools/page.tsx'),
      route('subscription', 'broker/subscription/page.tsx'),
    ]),
  ]),

  ...prefix('admin', [
    layout('admin/_layout.tsx', [
      index('admin/page.tsx'),
      route('tenants', 'admin/tenants/page.tsx'),
      route('users', 'admin/users/page.tsx'),
      route('roles', 'admin/roles/page.tsx'),
      route('plugins', 'admin/plugins/page.tsx'),
      route('doctypes', 'admin/doctypes/page.tsx'),
      route('migrations', 'admin/migrations/page.tsx'),
      route('hooks', 'admin/hooks/page.tsx'),
      route('config', 'admin/config/page.tsx'),
      route('api', 'admin/api/page.tsx'),
      route('workflows', 'admin/workflows/page.tsx'),
      route('audit', 'admin/audit/page.tsx'),
      route('pii', 'admin/pii/page.tsx'),
      route('compliance', 'admin/compliance/page.tsx'),
      route('slo', 'admin/slo/page.tsx'),
      route('security/reviews', 'admin/security.reviews/page.tsx'),
      route('doctype-studio', 'admin/doctype-studio/page.tsx'),
      route('workflow-designer', 'admin/workflow-designer/page.tsx'),
      route('approvals', 'admin/approvals/page.tsx'),
      route('mcp', 'admin/mcp/page.tsx'),
      route('tkgm', 'admin/tkgm/page.tsx'),
      route('reports', 'admin/reports/page.tsx'),
      route('reports/:section', 'admin/reports.$section/page.tsx'),
      route('auth-security', 'admin/auth-security/page.tsx'),
      route('observability', 'admin/observability/page.tsx'),
      route('ai-ops', 'admin/ai-ops/page.tsx'),
      route('agent-registry', 'admin/agent-registry/page.tsx'),
      route('orchestration', 'admin/orchestration/page.tsx'),
      route('agent-tasks', 'admin/agent-tasks/page.tsx'),
      route('rules', 'admin/rules/page.tsx'),
      route('feature-flags', 'admin/feature-flags/page.tsx'),
      route('tenant', 'admin/tenant/page.tsx'),
      route('modules', 'admin/modules/page.tsx'),
      route('modules/:id', 'admin/modules.$id/page.tsx'),
      route('notifications-templates', 'admin/notifications-templates/page.tsx'),
    ]),
  ]),

  ...prefix('agent', [
    layout('agent/_layout.tsx', [
      index('agent/page.tsx'),
      route('mcp', 'agent/mcp/page.tsx'),
      route('tools', 'agent/tools/page.tsx'),
      route('agents', 'agent/agents/page.tsx'),
      route('memory', 'agent/memory/page.tsx'),
      route('vectors', 'agent/vectors/page.tsx'),
      route('prompts', 'agent/prompts/page.tsx'),
      route('providers', 'agent/providers/page.tsx'),
      route('observability', 'agent/observability/page.tsx'),
      route('workflows', 'agent/workflows/page.tsx'),
      route('conversations', 'agent/conversations/page.tsx'),
    ]),
  ]),
] satisfies RouteConfig;
